// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2eosKWrDwp4tRGZGHrEuf5Qx1iaXAgik',
    appId: '1:391416986574:web:9339715126c41306fc099f',
    messagingSenderId: '391416986574',
    projectId: 'prmassignment-3d8f6',
    authDomain: 'prmassignment-3d8f6.firebaseapp.com',
    storageBucket: 'prmassignment-3d8f6.firebasestorage.app',
    measurementId: 'G-M61FH5SQTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9kSj8474lAJKad2IU7_Vls7L6vdtKM98',
    appId: '1:391416986574:android:50c66a751ccca4dafc099f',
    messagingSenderId: '391416986574',
    projectId: 'prmassignment-3d8f6',
    storageBucket: 'prmassignment-3d8f6.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBseIzGNl7fF1g-n-0nLsCAhBR2NOmBAdA',
    appId: '1:391416986574:ios:bb4f1acb4d1af539fc099f',
    messagingSenderId: '391416986574',
    projectId: 'prmassignment-3d8f6',
    storageBucket: 'prmassignment-3d8f6.firebasestorage.app',
    iosBundleId: 'com.example.prmproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2eosKWrDwp4tRGZGHrEuf5Qx1iaXAgik',
    appId: '1:391416986574:web:f829c766d6a235dafc099f',
    messagingSenderId: '391416986574',
    projectId: 'prmassignment-3d8f6',
    authDomain: 'prmassignment-3d8f6.firebaseapp.com',
    storageBucket: 'prmassignment-3d8f6.firebasestorage.app',
    measurementId: 'G-HL3K9QP5G3',
  );
}
